// <auto-generated />
namespace MemberRegistration.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ValidationMaxValueChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ValidationMaxValueChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201607102206329_ValidationMaxValueChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
